# .github/workflows/ci-cd.yml
name: CI/CD Pipeline for Accounting App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js (Latest Version)
        uses: actions/setup-node@v2
        with:
          node-version: '18.x' # Latest LTS or modify as needed

      - name: Install Dependencies with npm
        run: npm ci

      - name: Install Dependencies with Yarn
        run: yarn install

      - name: Install TypeScript
        run: npm install -g typescript

  test-and-build:
    needs: setup-environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js (Latest Version)
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install Dependencies with npm
        run: npm ci

      - name: Install Dependencies with Yarn
        run: yarn install

      - name: Lint Code
        run: npm run lint

      - name: Run Unit Tests
        run: npm test

      - name: Run End-to-End Tests
        run: npm run test:e2e

      - name: Build the App
        run: npm run build

  deploy-vercel:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Build Project
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

  deploy-github-pages:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Build Project for GitHub Pages
        run: npm run build && npx next export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out

  deploy-google-cloud:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy --quiet
          
